# Generated by Django 5.1.3 on 2024-11-20 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_farmer'),
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicale_number', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('empty_box', models.IntegerField()),
                ('wasteage', models.IntegerField()),
                ('prise', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('paid_status', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.farmer')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
    ]
