# Generated by Django 5.1.3 on 2024-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_farmer_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_bill',
            name='bill_number',
            field=models.IntegerField(null=True),
        ),
    ]
