# Generated by Django 5.1.3 on 2024-11-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_farmer_bill_labor_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_bill',
            name='empty_vehicale_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_bill',
            name='total_vehicale_weight',
            field=models.IntegerField(null=True),
        ),
    ]
