# Generated by Django 5.1.3 on 2024-11-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_phonepe_number_phonepe_transition'),
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phonepe_transition',
            new_name='Farmer_Phonepe_transition',
        ),
    ]
