# Generated by Django 5.1.3 on 2024-11-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_rename_phonepe_name_bank_account_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer_bank_transition',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='phonepe_number',
            name='shope',
        ),
        migrations.RemoveField(
            model_name='farmer_phonepe_transition',
            name='phonepe_number',
        ),
        migrations.AddField(
            model_name='farmer_phonepe_transition',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Bank_account',
        ),
        migrations.DeleteModel(
            name='Phonepe_number',
        ),
    ]
