# Generated by Django 5.1.3 on 2024-11-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_remove_farmer_bank_transition_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_bank_transition',
            name='bank_number',
            field=models.IntegerField(null=True),
        ),
    ]
