# Generated by Django 5.1.3 on 2024-12-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0015_company"),
        ("sunil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company_bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_cost_rate", models.FloatField()),
                ("product_cost_net_weight", models.FloatField()),
                ("product_cost_box", models.FloatField()),
                ("service_rate", models.FloatField()),
                ("service_net_weight", models.FloatField()),
                ("transport_rate", models.FloatField()),
                ("transport_box", models.FloatField()),
                ("stalk_rate", models.FloatField()),
                ("stalk_net_weight", models.FloatField()),
                ("wasteage_rate", models.FloatField()),
                ("wastage_weight", models.FloatField()),
                ("service_total_amount", models.FloatField()),
                ("wasteage_total_amount", models.FloatField()),
                ("product_cost_total_amount", models.FloatField()),
                ("stalk_total_amount", models.FloatField()),
                ("transport_total_amount", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="owner.company",
                    ),
                ),
                (
                    "farmer_bill",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="owner.farmer_bill",
                    ),
                ),
                (
                    "shope",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sunil.shope",
                    ),
                ),
            ],
        ),
    ]
