# Generated by Django 5.1.3 on 2024-12-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0017_company_bill_date_company_bill_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_bill",
            name="company_bill_number",
            field=models.IntegerField(default=1),
        ),
    ]
