# Generated by Django 5.1.3 on 2024-12-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0018_company_bill_company_bill_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_bill",
            name="added_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
