# Generated by Django 5.1.3 on 2024-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0019_company_bill_added_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images"
            ),
        ),
    ]
