# Generated by Django 5.1.3 on 2025-01-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_alter_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_bill',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company_bill',
            name='farmer_bill',
        ),
        migrations.RemoveField(
            model_name='company_bill',
            name='shope',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Company_bill',
        ),
    ]
