# Generated by Django 5.1.3 on 2025-01-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0022_company'),
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicale_number', models.CharField(max_length=100)),
                ('total_vehicale_weight', models.IntegerField(null=True)),
                ('empty_vehicale_weight', models.IntegerField(null=True)),
                ('weight', models.IntegerField()),
                ('empty_box', models.IntegerField()),
                ('wasteage', models.IntegerField()),
                ('prise', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('paid_status', models.IntegerField(default=0)),
                ('labor_amount', models.FloatField(null=True)),
                ('service_charge', models.FloatField(null=True)),
                ('eater', models.FloatField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('bill_number', models.IntegerField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.company')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
    ]
