# Generated by Django 5.1.3 on 2025-01-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0024_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_bill',
            name='leaf_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='logo_images'),
        ),
    ]
