# Generated by Django 5.1.3 on 2025-01-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0025_farmer_bill_leaf_weight_alter_logo_image'),
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer_cash_transition',
            name='farmer_bill',
        ),
        migrations.RemoveField(
            model_name='farmer_cash_transition',
            name='office_employee',
        ),
        migrations.RemoveField(
            model_name='farmer_cash_transition',
            name='shope',
        ),
        migrations.RemoveField(
            model_name='farmer_phonepe_transition',
            name='farmer_bill',
        ),
        migrations.RemoveField(
            model_name='farmer_phonepe_transition',
            name='office_employee',
        ),
        migrations.RemoveField(
            model_name='farmer_phonepe_transition',
            name='shope',
        ),
        migrations.CreateModel(
            name='Company_bank_transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_number', models.IntegerField(null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('company_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.company_bill')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
        migrations.CreateModel(
            name='Company_cash_transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('company_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.company_bill')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Phonepe_transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('company_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.company_bill')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
        migrations.DeleteModel(
            name='Farmer_bank_transition',
        ),
        migrations.DeleteModel(
            name='Farmer_cash_transition',
        ),
        migrations.DeleteModel(
            name='Farmer_Phonepe_transition',
        ),
    ]
