# Generated by Django 5.1.3 on 2025-01-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0027_farmer_bank_transition_farmer_cash_transition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_bill',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
