# Generated by Django 5.1.4 on 2025-01-03 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('shope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunil.shope')),
            ],
        ),
    ]
