# Generated by Django 5.1.1 on 2025-01-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_cart_orderdetail_ordermaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='shpoe',
            new_name='shope',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='shpoe',
            new_name='shope',
        ),
        migrations.RenameField(
            model_name='ordermaster',
            old_name='shpoe',
            new_name='shope',
        ),
    ]
