# Generated by Django 5.1.1 on 2025-01-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_rename_shpoe_cart_shope_and_more'),
        ('owner', '0029_remove_company_bill_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='employee',
        ),
        migrations.AddField(
            model_name='cart',
            name='office_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='office_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee'),
        ),
    ]
