# Generated by Django 5.1.1 on 2025-01-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_remove_cart_employee_remove_orderdetail_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermaster',
            old_name='employee',
            new_name='office_employee',
        ),
    ]
