# Generated by Django 5.1.4 on 2025-01-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_select_category_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_by',
            field=models.IntegerField(default=1),
        ),
    ]
