# Generated by Django 5.1.4 on 2025-01-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_category_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
